[[:csh    "ebnf/csh.ebnf"]
 [:tcsh   "ebnf/tcsh.ebnf"]
 [:sh     "ebnf/sh.ebnf"]
 [:bash   "ebnf/bash.ebnf"]
 [:perl   "ebnf/perl.ebnf"]
 [:python "ebnf/python.ebnf"]
 [:ace    "ebnf/ace.ebnf"]
 [:blast  "ebnf/blast.ebnf"]]
