S = (format-line | (line date-line)) #"[\s\S]*"
format-line = #"##fileformat=VCFv[\s\S^(?:\r|\r?\n)]*(?:\r|\r?\n)"
date-line = #"##fileDate=[\s\S^(?:\r|\r?\n)]*(?:\r|\r?\n)"
line = #"[\s\S^(?:\r|\r?\n)]*(?:\r|\r?\n)"